2016-11-29 15:34:12,008 Exception on /get_stims [GET]
Traceback (most recent call last):
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zorba/Dropbox/Neuro/psiturk/Swaps-no-fix/custom.py", line 131, in get_stims
    print load_from_db(params)
  File "/Users/zorba/Dropbox/Neuro/psiturk/Swaps-no-fix/custom.py", line 153, in load_from_db
    assert params["n_trials"]< len(all_trials)+1
AssertionError
2016-11-29 15:34:31,251 Exception on /get_stims [GET]
Traceback (most recent call last):
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zorba/Dropbox/Neuro/psiturk/Swaps-no-fix/custom.py", line 131, in get_stims
    load_from_db(params)
  File "/Users/zorba/Dropbox/Neuro/psiturk/Swaps-no-fix/custom.py", line 153, in load_from_db
    def load_from_db(params):
AssertionError
2016-11-29 15:34:54,846 Exception on /get_stims [GET]
Traceback (most recent call last):
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zorba/Dropbox/Neuro/psiturk/Swaps-no-fix/custom.py", line 131, in get_stims
    load_from_db(params)
  File "/Users/zorba/Dropbox/Neuro/psiturk/Swaps-no-fix/custom.py", line 155, in load_from_db
    assert params["n_trials"]< len(all_trials)+1
AssertionError
2016-11-29 15:34:54,851 Exception on /get_stims [GET]
Traceback (most recent call last):
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2016-11-29 15:34:59,826 Exception on /get_stims [GET]
Traceback (most recent call last):
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/zorba/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
